name: clone_fonus_app
description: "A mobile project by team BDDH base on Fonus"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  fluro: ^2.0.5
  provider: ^6.1.2
  equatable: ^2.0.7
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.1
  mask_text_input_formatter: ^2.0.0
  introduction_screen: ^3.1.17  # Package để tạo onboarding screen
  shared_preferences: ^2.2.3
  flutter_bloc: ^9.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
